Repository NASAKnights/InfiniteRecharge, pull requests merged in 2020-01, with the labels that each got.

#3 Create pull request for gradle fixes
  .gitignore
  .gradle/6.0-20191016123526+0000/fileChanges/last-build.bin
  .gradle/6.0-20191016123526+0000/fileContent/fileContent.lock
  .gradle/6.0-20191016123526+0000/fileHashes/fileHashes.lock
  .gradle/6.0-20191016123526+0000/gc.properties
  .gradle/6.0.1/executionHistory/executionHistory.bin
  .gradle/6.0.1/executionHistory/executionHistory.lock
  .gradle/6.0.1/fileChanges/last-build.bin
  .gradle/6.0.1/fileContent/fileContent.lock
  .gradle/6.0.1/fileHashes/fileHashes.bin
  .gradle/6.0.1/fileHashes/fileHashes.lock
  .gradle/6.0.1/fileHashes/resourceHashesCache.bin
  .gradle/6.0.1/gc.properties
  .gradle/6.0.1/javaCompile/classAnalysis.bin
  .gradle/6.0.1/javaCompile/jarAnalysis.bin
  .gradle/6.0.1/javaCompile/javaCompile.lock
  .gradle/6.0.1/javaCompile/taskHistory.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/vcs-1/gc.properties
  .idea/$CACHE_FILE$
  .idea/codeStyles/codeStyleConfig.xml
  .idea/jarRepositories.xml
  .idea/runConfigurations/Build_Robot.xml
  .idea/runConfigurations/Build___Deploy_Robot.xml
  .idea/runConfigurations/Build___Deploy_Robot_for_Debugging.xml
  .idea/runConfigurations/Clean_Build_Robot.xml
  .idea/runConfigurations/Clean_Build___Deploy_Robot.xml
  .idea/runConfigurations/Clean_Build___Deploy_Robot_for_Debugging.xml
  .idea/runConfigurations/Debug_Robot_via_IP.xml
  .idea/runConfigurations/Debug_Robot_via_USB.xml
  .idea/sbt.xml
  .idea/vcs.xml
  .wpilib/wpilib_preferences.json
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  vendordeps/Phoenix.json
  vendordeps/WPILibNewCommands.json
  vendordeps/WPILibOldCommands.json
  vendordeps/navx_frc.json
Labels: bug

#7 20200107 gradleworflow merge with master
  .gitignore
  src/main/java/xyz/nasaknights/infiniterecharge/Constants.java
  src/main/java/xyz/nasaknights/infiniterecharge/Main.java
  src/main/java/xyz/nasaknights/infiniterecharge/Robot.java
  src/main/java/xyz/nasaknights/infiniterecharge/RobotContainer.java
  src/main/java/xyz/nasaknights/infiniterecharge/commands/drivetrain/ArcadeDriveCommand.java
  src/main/java/xyz/nasaknights/infiniterecharge/commands/drivetrain/DriveCommand.java
  src/main/java/xyz/nasaknights/infiniterecharge/subsystems/DrivetrainSubsystem.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/MathUtils.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/RobotMap.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/control/motors/Lazy_TalonFX.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/control/motors/Lazy_TalonSRX.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/control/motors/Lazy_VictorSPX.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/control/motors/wpi/Lazy_WPI_TalonFX.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/control/motors/wpi/Lazy_WPI_TalonSRX.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/control/motors/wpi/Lazy_WPI_VictorSPX.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/control/pneumatics/Lazy_DoubleSolenoid.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/controller/PS4ControllerMappings.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/controllers/LogitechControllerMappings.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/controllers/PS4ControllerMappings.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/controllers/XboxControllerMappings.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/driver/DriverProfile.java
Labels: In Progress, enhancement

#12 Add compressor functionality
  src/main/java/xyz/nasaknights/infiniterecharge/Constants.java
  src/main/java/xyz/nasaknights/infiniterecharge/RobotContainer.java
Labels: In Progress, enhancement

#13 Update with current functioning drivetrain code
  src/main/java/xyz/nasaknights/infiniterecharge/Constants.java
  src/main/java/xyz/nasaknights/infiniterecharge/Robot.java
  src/main/java/xyz/nasaknights/infiniterecharge/RobotContainer.java
  src/main/java/xyz/nasaknights/infiniterecharge/commands/drivetrain/DriveCommand.java
  src/main/java/xyz/nasaknights/infiniterecharge/subsystems/DrivetrainSubsystem.java
  src/main/java/xyz/nasaknights/infiniterecharge/util/controllers/ControllerRegistry.java
Labels: enhancement
